# Generated by Django 6.0.2 on 2026-02-21 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pago',
            options={'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
        migrations.RenameField(
            model_name='pago',
            old_name='creado_en',
            new_name='fecha_pago',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='actualizado_en',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='id_transaccion',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='moneda',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='razon_fallo',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='stripe_payment_intent_id',
        ),
        migrations.AddField(
            model_name='pago',
            name='transaccion_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('fallido', 'Fallido')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('transferencia', 'Transferencia')], default='stripe', max_length=20),
        ),
    ]
