# Generated by Django 6.0.2 on 2026-02-22 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_producto_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categorias_secundarias',
            field=models.ManyToManyField(blank=True, related_name='productos_secundarios', to='catalog.categoria'),
        ),
    ]
