# Generated by Django 6.0.2 on 2026-02-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_producto_categorias_secundarias'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='volumen_ml',
            field=models.PositiveIntegerField(blank=True, help_text='Capacidad en mililitros (ml)', null=True),
        ),
    ]
