# Generated by Django 6.0.2 on 2026-02-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_producto_volumen_ml'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_oferta',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio en oferta (opcional). Si está presente se mostrará como precio actual.', max_digits=10, null=True),
        ),
    ]
